# Python problems on Datastructure


 ## Problem 1: Cryptocurrency Token Data
This data structure represents information about different cryptocurrency tokens listed on a decentralized exchange (DEX).

In [36]:
crypto_tokens = [
    {
        "name": "Token A",
        "symbol": "TKA",
        "blockchain": "Ethereum",
        "current_price_usd": 100.0,
        "transaction_history": [
            {
                "date": "2024-01-10",
                "prices": {
                    "open": 98.0,
                    "close": 100.0,
                    "high": 101.0,
                    "low": 97.0
                },
                "volume": 12000
            },
            {
                "date": "2024-01-09",
                "prices": {
                    "open": 97.0,
                    "close": 98.0,
                    "high": 99.0,
                    "low": 96.0
                },
                "volume": 15000
            }
        ],
        "supported_chains": ["Ethereum", "Polygon"]
    },
    {
        "name": "Token B",
        "symbol": "TKB",
        "blockchain": "Binance Smart Chain",
        "current_price_usd": 200.0,
        "transaction_history": [
            {
                "date": "2024-01-10",
                "prices": {
                    "open": 198.0,
                    "close": 200.0,
                    "high": 202.0,
                    "low": 196.0
                },
                "volume": 18000
            },
            {
                "date": "2024-01-09",
                "prices": {
                    "open": 196.0,
                    "close": 198.0,
                    "high": 199.0,
                    "low": 195.0
                },
                "volume": 17000
            }
        ],
        "supported_chains": ["Binance Smart Chain", "Avalanche"]
    },
    {
        "name": "Token C",
        "symbol": "TKC",
        "blockchain": "Solana",
        "current_price_usd": 300.0,
        "transaction_history": [
            {
                "date": "2024-01-10",
                "prices": {
                    "open": 295.0,
                    "close": 300.0,
                    "high": 302.0,
                    "low": 294.0
                },
                "volume": 22000
            },
            {
                "date": "2024-01-09",
                "prices": {
                    "open": 294.0,
                    "close": 295.0,
                    "high": 296.0,
                    "low": 293.0
                },
                "volume": 21000
            }
        ],
        "supported_chains": ["Solana", "Fantom"]
    }
]

```python
Q1: Read Data
Task: Display the current price of "Token B".
Q2: Write Data  
Task: Add a new token "Token D" with some initial data to the `crypto_tokens` list.

Q3: Update Data  
Task: Update the current price of "Token C" to 310.0.

Q4: Delete Data  
Task: Remove the transaction history for "Token A" on "2024-01-09".

Q5: Read Nested Data  
Task: Display the closing price of "Token B" on "2024-01-10".

Q6: Update Nested Data  
Task: Change the opening price of "Token A" on "2024-01-10" to 99.0.

Q7: Add Nested Data  
Task: Add a new transaction history entry for "Token C" on "2024-01-11".

Q8: Delete an Item from a List Inside a Dictionary  
Task: Remove "Avalanche" from the supported chains of "Token B".

## Solution

### Q1: Read Data  
Task: Display the current price of "Token B".

In [37]:
crypto_tokens[1]["current_price_usd"]

200.0

### Q2: Write Data  
Task: Add a new token "Token D" with some initial data to the `crypto_tokens` list.

In [38]:
crypto_tokens.append({
        "name": "Token D",
        "symbol": "KRUYS",
        "blockchain": "Solana",
        "current_price_usd": 1000.0,
        "transaction_history": [
            {
                "date": "2024-05-11",
                "prices": {
                    "open": 900.0,
                    "close": 1000.0,
                    "high": 1300.0,
                    "low": 890.0
                },
                "volume": 2200000
            },
            {
                "date": "2024-05-10",
                "prices": {
                    "open": 850.0,
                    "close": 900.0,
                    "high": 980.0,
                    "low": 807.0
                },
                "volume": 2100000
            }
        ],
        "supported_chains": ["Solana", "Ethereum", "Polygon"]
    }
)

crypto_tokens

[{'name': 'Token A',
  'symbol': 'TKA',
  'blockchain': 'Ethereum',
  'current_price_usd': 100.0,
  'transaction_history': [{'date': '2024-01-10',
    'prices': {'open': 98.0, 'close': 100.0, 'high': 101.0, 'low': 97.0},
    'volume': 12000},
   {'date': '2024-01-09',
    'prices': {'open': 97.0, 'close': 98.0, 'high': 99.0, 'low': 96.0},
    'volume': 15000}],
  'supported_chains': ['Ethereum', 'Polygon']},
 {'name': 'Token B',
  'symbol': 'TKB',
  'blockchain': 'Binance Smart Chain',
  'current_price_usd': 200.0,
  'transaction_history': [{'date': '2024-01-10',
    'prices': {'open': 198.0, 'close': 200.0, 'high': 202.0, 'low': 196.0},
    'volume': 18000},
   {'date': '2024-01-09',
    'prices': {'open': 196.0, 'close': 198.0, 'high': 199.0, 'low': 195.0},
    'volume': 17000}],
  'supported_chains': ['Binance Smart Chain', 'Avalanche']},
 {'name': 'Token C',
  'symbol': 'TKC',
  'blockchain': 'Solana',
  'current_price_usd': 300.0,
  'transaction_history': [{'date': '2024-01-10',
 

### Q3: Update Data  
Task: Update the current price of "Token C" to 310.0.

In [39]:
crypto_tokens[2]["current_price_usd"] = 310.0
crypto_tokens[2]["current_price_usd"]

310.0

### Q4: Delete Data  
Task: Remove the transaction history for "Token A" on "2024-01-09".

In [40]:
crypto_tokens[0]["transaction_history"].pop(1)
crypto_tokens[0]["transaction_history"]


[{'date': '2024-01-10',
  'prices': {'open': 98.0, 'close': 100.0, 'high': 101.0, 'low': 97.0},
  'volume': 12000}]

### Q5: Read Nested Data  
Task: Display the closing price of "Token B" on "2024-01-10".

In [41]:
crypto_tokens[1]["transaction_history"][0]["prices"]["close"]

200.0

### Q6: Update Nested Data  
Task: Change the opening price of "Token A" on "2024-01-10" to 99.0.

In [42]:
crypto_tokens[0]["transaction_history"][0]["prices"]["open"] = 99.0
crypto_tokens

[{'name': 'Token A',
  'symbol': 'TKA',
  'blockchain': 'Ethereum',
  'current_price_usd': 100.0,
  'transaction_history': [{'date': '2024-01-10',
    'prices': {'open': 99.0, 'close': 100.0, 'high': 101.0, 'low': 97.0},
    'volume': 12000}],
  'supported_chains': ['Ethereum', 'Polygon']},
 {'name': 'Token B',
  'symbol': 'TKB',
  'blockchain': 'Binance Smart Chain',
  'current_price_usd': 200.0,
  'transaction_history': [{'date': '2024-01-10',
    'prices': {'open': 198.0, 'close': 200.0, 'high': 202.0, 'low': 196.0},
    'volume': 18000},
   {'date': '2024-01-09',
    'prices': {'open': 196.0, 'close': 198.0, 'high': 199.0, 'low': 195.0},
    'volume': 17000}],
  'supported_chains': ['Binance Smart Chain', 'Avalanche']},
 {'name': 'Token C',
  'symbol': 'TKC',
  'blockchain': 'Solana',
  'current_price_usd': 310.0,
  'transaction_history': [{'date': '2024-01-10',
    'prices': {'open': 295.0, 'close': 300.0, 'high': 302.0, 'low': 294.0},
    'volume': 22000},
   {'date': '2024-01-09

### Q7: Add Nested Data  
Task: Add a new transaction history entry for "Token C" on "2024-01-11".

In [43]:
crypto_tokens[2]["transaction_history"].insert(0, {
    'date': '2024-01-11',
    'prices': {'open': 300.0, 'close': 460.0, 'high': 490.0, 'low': 294.0},
    'volume': 23000
})
crypto_tokens[2]["transaction_history"][0]

{'date': '2024-01-11',
 'prices': {'open': 300.0, 'close': 460.0, 'high': 490.0, 'low': 294.0},
 'volume': 23000}

### Q8: Delete an Item from a List Inside a Dictionary  
Task: Remove "Avalanche" from the supported chains of "Token B".

In [44]:
crypto_tokens[1]['supported_chains'].remove("Avalanche")
crypto_tokens[1]['supported_chains']

['Binance Smart Chain']

## Problem 2: Crypto Investment Portfolio
This data structure represents a crypto investment portfolio, including various assets like tokens, stablecoins, and NFTs, along with their holdings and performance metrics.


In [45]:
crypto_portfolio = {
    "investor_name": "Jane Doe",
    "portfolio_id": "JD1234",
    "assets": {
        "tokens": [
            {
                "ticker": "ETH",
                "quantity": 50,
                "purchase_price": 2000.00,
                "current_price": 2100.00
            },
            {
                "ticker": "BTC",
                "quantity": 30,
                "purchase_price": 40000.00,
                "current_price": 41000.00
            }
        ],
        "stablecoins": [
            {
                "identifier": "USDC",
                "quantity": 10000,
                "purchase_price": 1.00,
                "current_price": 1.00,
                "peg_currency": "USD"
            }
        ],
        "nfts": [
            {
                "name": "CryptoArt 123",
                "quantity": 1,
                "purchase_price": 5000.00,
                "current_price": 5500.00
            }
        ]
    },
    "cash_holdings_usd": 10000.00,
    "investment_goals": {"retirement": 2035, "education": 2025}
}

```python


Q1: Read Data  
Task: Display the current price of the NFT "CryptoArt 123".

Q2: Write Data  
Task: Add a new token with ticker "ADA", 1000 units, a purchase price of 1.50, and a current price of 1.60 to the tokens in the assets.

Q3: Update Data  
Task: Update the quantity of "ETH" token to 60.

Q4: Delete Data  
Task: Remove the stablecoin with identifier "USDC" from the stablecoins in assets.

Q5: Read Nested Data  
Task: Display the peg currency of the stablecoin in the portfolio.

Q6: Update Nested Data  
Task: Change the current price of "BTC" token to 41500.00.

Q7: Add Nested Data  
Task: Add a new goal "vacation" set for the year 2028 in the investment goals.

Q8: Delete an Item from a List Inside a Dictionary  
Task: Remove the NFT "CryptoArt 123" from the portfolio.

## Solution

### Q1: Read Data  
Task: Display the current price of the NFT "CryptoArt 123".

In [46]:
crypto_portfolio["assets"]["nfts"][0]["current_price"]

5500.0

###  Q2: Write Data  
Task: Add a new token with ticker "ADA", 1000 units, a purchase price of 1.50, and a current price of 1.60 to the tokens in the assets.

In [47]:
crypto_portfolio["assets"]["tokens"].append({
                "ticker": "ADA",
                "quantity": 1000,
                "purchase_price": 1.50,
                "current_price": 1.60
            })
crypto_portfolio["assets"]["tokens"]

[{'ticker': 'ETH',
  'quantity': 50,
  'purchase_price': 2000.0,
  'current_price': 2100.0},
 {'ticker': 'BTC',
  'quantity': 30,
  'purchase_price': 40000.0,
  'current_price': 41000.0},
 {'ticker': 'ADA',
  'quantity': 1000,
  'purchase_price': 1.5,
  'current_price': 1.6}]

### Q3: Update Data  
Task: Update the quantity of "ETH" token to 60

In [48]:
crypto_portfolio["assets"]["tokens"][0]["quantity"] = 60
crypto_portfolio["assets"]["tokens"][0]

{'ticker': 'ETH',
 'quantity': 60,
 'purchase_price': 2000.0,
 'current_price': 2100.0}

### Q4: Delete Data  
Task: Remove the stablecoin with identifier "USDC" from the stablecoins in assets.

In [49]:
crypto_portfolio["assets"]["stablecoins"].pop(0)
crypto_portfolio["assets"]

{'tokens': [{'ticker': 'ETH',
   'quantity': 60,
   'purchase_price': 2000.0,
   'current_price': 2100.0},
  {'ticker': 'BTC',
   'quantity': 30,
   'purchase_price': 40000.0,
   'current_price': 41000.0},
  {'ticker': 'ADA',
   'quantity': 1000,
   'purchase_price': 1.5,
   'current_price': 1.6}],
 'stablecoins': [],
 'nfts': [{'name': 'CryptoArt 123',
   'quantity': 1,
   'purchase_price': 5000.0,
   'current_price': 5500.0}]}

### Q5: Read Nested Data  
Task: Display the peg currency of the stablecoin in the portfolio.

In [53]:
crypto_portfolio = {
    "investor_name": "Jane Doe",
    "portfolio_id": "JD1234",
    "assets": {
        "tokens": [
            {
                "ticker": "ETH",
                "quantity": 50,
                "purchase_price": 2000.00,
                "current_price": 2100.00
            },
            {
                "ticker": "BTC",
                "quantity": 30,
                "purchase_price": 40000.00,
                "current_price": 41000.00
            }
        ],
        "stablecoins": [
            {
                "identifier": "USDC",
                "quantity": 10000,
                "purchase_price": 1.00,
                "current_price": 1.00,
                "peg_currency": "USD"
            }
        ],
        "nfts": [
            {
                "name": "CryptoArt 123",
                "quantity": 1,
                "purchase_price": 5000.00,
                "current_price": 5500.00
            }
        ]
    },
    "cash_holdings_usd": 10000.00,
    "investment_goals": {"retirement": 2035, "education": 2025}
}

crypto_portfolio["assets"]["stablecoins"][0]["peg_currency"]

'USD'

### Q6: Update Nested Data  
Task: Change the current price of "BTC" token to 41500.00.

In [54]:
crypto_portfolio["assets"]["tokens"][1]["current_price"] = 41500.00
crypto_portfolio["assets"]["tokens"][1]

{'ticker': 'BTC',
 'quantity': 30,
 'purchase_price': 40000.0,
 'current_price': 41500.0}

### Q7: Add Nested Data  
Task: Add a new goal "vacation" set for the year 2028 in the investment goals.

In [55]:
crypto_portfolio["investment_goals"].update({"vacation": 2028})
crypto_portfolio["investment_goals"]

{'retirement': 2035, 'education': 2025, 'vacation': 2028}

### Q8: Delete an Item from a List Inside a Dictionary  
Task: Remove the NFT "CryptoArt 123" from the portfolio.

In [57]:
crypto_portfolio["assets"]["nfts"].remove({
    "name": "CryptoArt 123",
    "quantity": 1,
    "purchase_price": 5000.00,
    "current_price": 5500.00
})
crypto_portfolio["assets"]["nfts"]

[]

## Problem 4: Cryptocurrency Exchange Rates
This data structure tracks cryptocurrency exchange rates relative to a base stablecoin.



In [75]:
crypto_exchange = {
    "base_currency": "USDT",
    "exchange_rates": {
        "ETH": {
            "current_rate": 0.0005,
            "historical_rates": [
                {"date": "2024-01-10", "rate": 0.00048},
                {"date": "2024-01-09", "rate": 0.00049}
            ]
        },
        "BTC": {
            "current_rate": 0.000025,
            "historical_rates": [
                {"date": "2024-01-10", "rate": 0.000024},
                {"date": "2024-01-09", "rate": 0.000026}
            ]
        }
    }
}

```python

Q1: Read Data  
Task: Display the current exchange rate for ETH.

Q2: Write Data  
Task: Add a new currency "ADA" with a current rate of 0.0015 and two historical rates: 0.0016 on "2024-01-10" and 0.0017 on "2024-01-09".

Q3: Update Data  
Task: Update the current exchange rate of BTC to 0.000027.

Q4: Delete Data  
Task: Remove the historical rates for ETH.
Q5: Read Nested Data  
Task: Display the exchange rate of BTC on "2024-01-10".

Q6: Update Nested Data  
Task: Change the rate of ETH on "2024-01-10" to 0.00047.

Q7: Add Nested Data  
Task: Add a new historical rate for BTC on "2024-01-11" with a rate of 0.000023.

Q8: Delete an Item from a List Inside a Dictionary  
Task: Remove the historical rate of BTC on "2024-01-09".



### Q1: Read Data  
Task: Display the current exchange rate for ETH.

In [76]:
crypto_exchange["exchange_rates"]["ETH"]["current_rate"]

0.0005

### Q2: Write Data  
Task: Add a new currency "ADA" with a current rate of 0.0015 and two historical rates: 0.0016 on "2024-01-10" and 0.0017 on "2024-01-09".

In [77]:
crypto_exchange["exchange_rates"]["ADA"] = {
    "current_rate": 0.0015,
    "historical_rates": [
        {"date": "2024-01-10", "rate": 0.0016},
        {"date": "2024-01-09", "rate": 0.0017}
    ]
}
crypto_exchange["exchange_rates"]

{'ETH': {'current_rate': 0.0005,
  'historical_rates': [{'date': '2024-01-10', 'rate': 0.00048},
   {'date': '2024-01-09', 'rate': 0.00049}]},
 'BTC': {'current_rate': 2.5e-05,
  'historical_rates': [{'date': '2024-01-10', 'rate': 2.4e-05},
   {'date': '2024-01-09', 'rate': 2.6e-05}]},
 'ADA': {'current_rate': 0.0015,
  'historical_rates': [{'date': '2024-01-10', 'rate': 0.0016},
   {'date': '2024-01-09', 'rate': 0.0017}]}}

### Q3: Update Data  
Task: Update the current exchange rate of BTC to 0.000027.

In [78]:
crypto_exchange["exchange_rates"]["BTC"]["current_rate"] = 0.000027
crypto_exchange["exchange_rates"]

{'ETH': {'current_rate': 0.0005,
  'historical_rates': [{'date': '2024-01-10', 'rate': 0.00048},
   {'date': '2024-01-09', 'rate': 0.00049}]},
 'BTC': {'current_rate': 2.7e-05,
  'historical_rates': [{'date': '2024-01-10', 'rate': 2.4e-05},
   {'date': '2024-01-09', 'rate': 2.6e-05}]},
 'ADA': {'current_rate': 0.0015,
  'historical_rates': [{'date': '2024-01-10', 'rate': 0.0016},
   {'date': '2024-01-09', 'rate': 0.0017}]}}

### Q4: Delete Data  
Task: Remove the historical rates for ETH.

In [79]:
del crypto_exchange["exchange_rates"]["ETH"]["historical_rates"]
crypto_exchange["exchange_rates"]

{'ETH': {'current_rate': 0.0005},
 'BTC': {'current_rate': 2.7e-05,
  'historical_rates': [{'date': '2024-01-10', 'rate': 2.4e-05},
   {'date': '2024-01-09', 'rate': 2.6e-05}]},
 'ADA': {'current_rate': 0.0015,
  'historical_rates': [{'date': '2024-01-10', 'rate': 0.0016},
   {'date': '2024-01-09', 'rate': 0.0017}]}}

### Q5: Read Nested Data  
Task: Display the exchange rate of BTC on "2024-01-10".

In [80]:
crypto_exchange['exchange_rates']['BTC']['historical_rates'][0]["rate"]

2.4e-05

### Q6: Update Nested Data  
Task: Change the rate of ETH on "2024-01-10" to 0.00047.

In [82]:
crypto_exchange['exchange_rates']['ETH']["historical_rates"] = [
	{"date": "2024-01-10", "rate": 0.00047},
	{"date": "2024-01-09", "rate": 0.00049}
]

crypto_exchange['exchange_rates']

{'ETH': {'current_rate': 0.0005,
  'historical_rates': [{'date': '2024-01-10', 'rate': 0.00047},
   {'date': '2024-01-09', 'rate': 0.00049}]},
 'BTC': {'current_rate': 2.7e-05,
  'historical_rates': [{'date': '2024-01-10', 'rate': 2.4e-05},
   {'date': '2024-01-09', 'rate': 2.6e-05}]},
 'ADA': {'current_rate': 0.0015,
  'historical_rates': [{'date': '2024-01-10', 'rate': 0.0016},
   {'date': '2024-01-09', 'rate': 0.0017}]}}

### Q7: Add Nested Data  
Task: Add a new historical rate for BTC on "2024-01-11" with a rate of 0.000023.

In [83]:
crypto_exchange['exchange_rates']['BTC']["historical_rates"].insert(0, {
    'date': '2024-01-11',
    'rate': 0.000023
} )
crypto_exchange['exchange_rates']['BTC']["historical_rates"]

[{'date': '2024-01-11', 'rate': 2.3e-05},
 {'date': '2024-01-10', 'rate': 2.4e-05},
 {'date': '2024-01-09', 'rate': 2.6e-05}]

### Q8: Delete an Item from a List Inside a Dictionary  
Task: Remove the historical rate of BTC on "2024-01-09".

In [84]:
del crypto_exchange['exchange_rates']['BTC']["historical_rates"][1]
crypto_exchange['exchange_rates']['BTC']["historical_rates"]

[{'date': '2024-01-11', 'rate': 2.3e-05},
 {'date': '2024-01-09', 'rate': 2.6e-05}]

Check if user is above 18 and verified to proceed

Print Access Granted if age > 18 or has parents permission

Use Not to check if a wallet is not blacklisted

In [90]:
age = input("What is your Age and are you verified? Please enter your age in numbers" ) 
verified = input("Did you get your parent's permission? please enter 'yes' or 'no': ")
Wallet_blacklisted = False 

if int(age) > 18 or verified.lower() == 'yes':
    print("Access Granted")
else:
    print("Access Denied")

if not Wallet_blacklisted:
    print("Wallet is not blacklisted, you can proceed.")
else:
    print("Wallet is blacklisted, access denied.")
# --- IGNORE ---    

Access Granted
Wallet is not blacklisted, you can proceed.


In [91]:
even = []
for i in range(1, 101):
    if i % 2 == 0:
        even.append(i)
print("Even numbers from 1 to 100:", even)

Even numbers from 1 to 100: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [93]:
even =[]
i = 0
while True:
    if i > 100:
        break
    if i % 2 == 0:
        even.append(i)
    i += 1
print("Even numbers from 1 to 100:", even)

Even numbers from 1 to 100: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
